package jp.asojuku.testmanagement.bo;

import java.sql.SQLException;

import javax.naming.NamingException;

import jp.asojuku.testmanagement.dto.TestSeachResultDto;
import jp.asojuku.testmanagement.entity.TestListEntity;
import jp.asojuku.testmanagement.exception.SystemErrorExcepton;
import jp.asojuku.testmanagement.model.Dbcontrol;

public class DeleteTestInfoBo {
	private static final String TEST_INFO_DELETE_SQL ="DELETE FROM test "+
			"WHERE "+ TestListEntity.TEST_ID + " = ?";
	private static final int  TEST_INFO_DELETE_SQL_IDX = 1;
	
	public int testdeleteinfo(String testId) throws  SystemErrorExcepton, NamingException{
		int result = 0;
		Dbcontrol db = new Dbcontrol();
		try{
			db.connect();
			db.prepareStatement(TEST_INFO_DELETE_SQL);
			db.setString(TEST_INFO_DELETE_SQL_IDX, testId);
			result = db.executeUpdate();
			db.commit();
			
		}catch(NamingException e){
			System.out.println(e.getMessage());
			
		} catch (SQLException e) {
			SafeRollback(db);
			System.out.println(e.getMessage());
			// TODO 自動生成された catch ブロック
			e.printStackTrace();
		}
		return result;
	}
	public TestSeachResultDto testdeleteinformation(String testId){
		TestSeachResultDto result = new TestSeachResultDto();
		return result;
	}
	private void SafeRollback(Dbcontrol db){

		try {
			db.rollback();
		} catch (SQLException e) {
			//ログの出力のみ
			System.out.println("ロールバックに失敗しました："+e);
		}

	}

}
